import type { Metadata } from "next";
import localFont from "next/font/local";
import TrpcProvider from '@/lib/trpc/Provider';
import { ClerkProvider } from '@clerk/nextjs';
import { Inter } from 'next/font/google';
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// (可选) Clerk 默认是英文，如果你需要中文
import { zhCN } from "@clerk/localizations";
import { Header } from "./components/custom/Header";

const inter = Inter({ subsets: ['latin'] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // 使用 ClerkProvider 包裹你的应用
    <ClerkProvider localization={zhCN}> 
      <html lang="zh">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Header />
        <TrpcProvider>{children}</TrpcProvider>
      </body>
    </html>
    </ClerkProvider>
  );
}
